version: '3.8'

services:
  django:
    container_name: uprojects_django
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/home/backend/
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env.dev
    networks:
      - framework
  react:
    container_name: uprojects_react
    build: ./frontend
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d/:ro
    ports:
      - '3000:80'
    env_file:
      - frontend/.env
    networks:
      - framework
networks:
  framework:
    name: framework
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
