name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: Build and Test
        run: |
          # Build and test react
          cd ./frontend
          npm install
          npm run build
          docker build -t registry.${{ secrets.COFFEEHOUSE_HOST }}:5000/uprojects_react .
          # TODO - run tests

          # Build and test django
          cd ../backend
          docker build -f Dockerfile.prod -t registry.${{ secrets.COFFEEHOUSE_HOST }}:5000/uprojects_django .
          # TODO - run tests

      - name: Install miredo (Establish IPv6)
        run: |
          sudo apt install -y miredo
          sudo sed -i 's/ServerAddress	teredo-debian.remlab.net/ServerAddress teredo.iks-jena.de/g' /etc/miredo.conf
          sudo miredo
          cat /etc/miredo.conf
          sleep 1
          ip addr
          sleep 1
          ip addr
          sleep 1
          ip addr

      - name: Push Docker Images
        run: |
          # Push React
          docker push registry.${{ secrets.COFFEEHOUSE_HOST }}:5000/uprojects_react
          # Push Django
          docker push registry.${{ secrets.COFFEEHOUSE_HOST }}:5000/uprojects_django

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.COFFEEHOUSE_HOST }}
          username: ${{ secrets.COFFEEHOUSE_USER }}
          key: ${{ secrets.COFFEEHOUSE_KEY }}
          port: 22
          script: ls -lsa
            # cd ${{ secrets.COFFEEHOUSE_COMPOSE }}
            # docker-compose down
            # docker-compose up -d
      # - name: Set up Remote Connection
      #   uses: webfactory/ssh-agent@v0.5.2
      #   with:
      #     ssh-private-key: ${{ secrets.COFFEEHOUSE_KEY }}

      # - name: SSH Into the Server and Restart Docker Compose
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ${{ secrets.COFFEEHOUSE_USER }}@${{ secrets.COFFEEHOUSE_HOST }} 'cd ${{ secrets.COFFEEHOUSE_COMPOSE }} && docker-compose down && docker-compose up -d'
      # # - name: Docker-Compose Remote Deployment
      #   uses: alex-ac/github-action-ssh-docker-compose@master
      #   with:
      #     ssh_host: ${{ secrets.COFFEEHOUSE_HOST }}
      #     ssh_private_key: ${{ secrets.COFFEEHOUSE_KEY }}
      #     ssh_user: ${{ secrets.COFFEEHOUSE_USER }}
      #     docker_compose_filename: ${{ secrets.COFFEEHOUSE_COMPOSE }}
